### PR TITLE
Crudini for python3

### PR DESCRIPTION
**Pull request by tzuie**
tested on python 3.6.5

### CODE REVIEW

**Comment by tzuie** [comment]
Yes, you can.

**Comment by dirkmueller** [comment]
there is an issue in the patch, the hashlib usage needs to be updated for python3 as well, otherwise it will throw an exception about not being able to use string

**Comment by razorsedge** [comment]
Plus 1 for Python 3 support.

**Comment by pixelb** [comment]
closing this as it was handled in pull/54

**Pull request closed without merging**
